### ISSUE TITLE
Implement body detection/tracking

### ISSUE THREAD

**Issue by AidenDurrant** [AidenDurrant/Interactive-Photobooth#3]
Write and implement code to create algorithm/software to allow the hardware to detect a user’s body, and their defining structure in real time. This will be written in C#/C++ as these are the supported languages for the Kinect SDK and will allow us to fully utilise the features.

**Comment by AidenDurrant** [comment]
I'll have a look tonight lads, my kinect arrived while i was at work:) I'll get cracking x

**Comment by TGRHavoc** [comment]
I've sort of got it working on [base-program](https://github.com/AidenDurrant/Interactive-Photobooth/tree/base-program) it's really off though. 

If you can get it to be more accurate etc, that would be amazing 😁

**Comment by TGRHavoc** [comment]
I think we now have solid body detection and tracking. Just need to superimpose clothes onto users.
