### ISSUE TITLE
Design Props

### ISSUE THREAD

**Issue by AidenDurrant** [AidenDurrant/Interactive-Photobooth#4]
Design and create the props on paper and within adobe design software. These will be used to superimpose on the users tracked body/face.

**Comment by TGRHavoc** [comment]
- [X] Hats
- [X] Shirts
- [ ] Hand props

**Comment by TGRHavoc** [comment]
Since we've decided not to have hand props, I'd say this has been completed 😄 

So, going to close the issue.
