### ISSUE TITLE
Implement Photo/Screenshot taking 

### ISSUE THREAD

**Issue by AidenDurrant** [AidenDurrant/Interactive-Photobooth#7]
Implement a screenshot feature to allow the users to share their (creations?) with others.

**Comment by TGRHavoc** [comment]
See 4bb5996741e03abf2972ea9c668a3d26fb45b5f1 and 122c45ba6d1aa405074cde731e91543030c5b6de 😄

**Comment by TGRHavoc** [comment]
I'd like to think this has been completed with commit 4ddbd453716bbc290ece7cfd1d4213bedfa414ab.

So, closing this issue 😄
