### ISSUE TITLE
Gesture controls with the UI

### ISSUE THREAD

**Issue by AidenDurrant** [AidenDurrant/Interactive-Photobooth#8]
Implement gesture control with the user interface using the technologies used for body tracking. This will control the extra functionality of the prototype. This will be written in C#/C++, using Microsoft Kinect SDK’s available online.

**Comment by TGRHavoc** [comment]
Got this working 😄 

It's probably not the best implementation but, it works so... It's over on the [features/guesture-controls](/AidenDurrant/Interactive-Photobooth/tree/feature/guesture-controls) (ignore the bad spelling 😛).

@Pearr, you might want to get the buttons ready for integration, if so do the following:

- Add "Box Collider 2D" to the button
- Change the offset
  - `x` should be the image's `width/2` (e.g. if width is 150 then offset is 75)
  - `y` should be the image's `-(height/2)` (e.g. if height is 150 then offset is -75)
- Change the size (should match the image's size)

**Comment by TGRHavoc** [comment]
@JimmyCross Disregard my last comment. I've updated the system so, you don't have to add the box collider to the buttons.

I'm marking this issue closed as controlling the UI was implemented with commit 987bcd65627f8f8c0af5d3cbedd43b7152ebabdc
